let tableauSongs = [
  "Adieu poulet",
  "Apocalypse Now",
  "Au Nom de la Loi",
  "Back to the future",
  "Banzaï",
  "Borsalino",
  "Chariots de feu",
  "Christine",
  "Coup de tête",
  "Dîner de cons",
  "Drôles de dames",
  "Hawaï Police d Etat",
  "Il était une fois dans l ouest",
  "Je suis timide Mais je me soigne",
  "Jean Philippe",
  "La  chevre",
  "La boum 2",
  "La course à l échalotte",
  "La dérobade",
  "La guerre des polices",
  "La liste de Schindler",
  "La petite maison dans la prairie",
  "La septième cible",
  "La soif de l or",
  "La totale !",
  "La zizanie",
  "L affaire Thomas Crown",
  "L aile ou la cuisse",
  "Le battant",
  "Le Bon, la Brute et le Truand",
  "Le château de ma Mère",
  "Le clan des Siciliens",
  "Le flic de Beverly Hills",
  "Le grand blond avec une chaussure noire",
  "Le jouet",
  "Le marginal",
  "Le placard",
  "Le professionnel",
  "Le retour du grand blond",
  "Le silence des agneaux",
  "L emmerdeur",
  "Les bracelets rouges",
  "Les compères",
  "Les fugitifs",
  "Les sous-doués en vacances",
  "L étudiante",
  "L exorciste",
  "L inspecteur La Bavure",
  "Ma sorcière bien aimée",
  "Médecins de nuit",
  "Nous irons tous au paradis",
  "Orange mécanique",
  "Rain Man",
  "Rambo",
  "Rocky",
  "Starsky et Hutch",
  "Superman",
  "Taxi Driver",
  "Un homme et une femme",
  "Un taxi pour tobrouk",
  "Vol au-dessus d un nid de coucou",
];
